#!/bin/sh
systemctl enable local.ir-keytable-mpd.service
systemctl enable local.ir-event-mpd.service
systemctl enable local.mechanical-controls-mpd.service
systemctl daemon-reload
systemctl start local.ir-keytable-mpd.service
systemctl start local.ir-event-mpd.service
systemctl start local.mechanical-controls-mpd.service


